// The nối từ wire contract.
//
// This file is the single source of truth for everything crossing the
// WebSocket. Both the Go server and the JavaScript client are generated from
// it; neither side hand-writes a message type. Every frame is a binary
// protobuf message — there is no JSON fallback and no text frame.
//
// Compatibility rules, because a deployed client outlives a deploy:
//   - changes are additive only;
//   - a removed field's tag goes to `reserved`, never to another field;
//   - Hello.protocol_version lets the server refuse an incompatible client
//     with a readable error instead of failing to decode.

// @generated by protoc-gen-es v2.14.1 with parameter "target=js+dts,import_extension=.js"
// @generated from file noitu/v1/game.proto (package noitu.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file noitu/v1/game.proto.
 */
export declare const file_noitu_v1_game: GenFile;

/**
 * Hello opens a session. nickname is a *request*: the server sanitizes it and
 * reports what it actually stored in Welcome.accepted_nickname.
 *
 * @generated from message noitu.v1.Hello
 */
export declare type Hello = Message<"noitu.v1.Hello"> & {
  /**
   * @generated from field: uint32 protocol_version = 1;
   */
  protocolVersion: number;

  /**
   * Empty on a fresh session; a token from a previous Welcome to resume one.
   *
   * @generated from field: string resume_token = 2;
   */
  resumeToken: string;

  /**
   * @generated from field: string nickname = 3;
   */
  nickname: string;
};

/**
 * Describes the message noitu.v1.Hello.
 * Use `create(HelloSchema)` to create a new message.
 */
export declare const HelloSchema: GenMessage<Hello>;

/**
 * @generated from message noitu.v1.StartBotGame
 */
export declare type StartBotGame = Message<"noitu.v1.StartBotGame"> & {
  /**
   * @generated from field: noitu.v1.Difficulty difficulty = 1;
   */
  difficulty: Difficulty;
};

/**
 * Describes the message noitu.v1.StartBotGame.
 * Use `create(StartBotGameSchema)` to create a new message.
 */
export declare const StartBotGameSchema: GenMessage<StartBotGame>;

/**
 * @generated from message noitu.v1.CreateRoom
 */
export declare type CreateRoom = Message<"noitu.v1.CreateRoom"> & {
};

/**
 * Describes the message noitu.v1.CreateRoom.
 * Use `create(CreateRoomSchema)` to create a new message.
 */
export declare const CreateRoomSchema: GenMessage<CreateRoom>;

/**
 * @generated from message noitu.v1.JoinRoom
 */
export declare type JoinRoom = Message<"noitu.v1.JoinRoom"> & {
  /**
   * @generated from field: string room_code = 1;
   */
  roomCode: string;
};

/**
 * Describes the message noitu.v1.JoinRoom.
 * Use `create(JoinRoomSchema)` to create a new message.
 */
export declare const JoinRoomSchema: GenMessage<JoinRoom>;

/**
 * SubmitWord carries the turn it was typed for. The server rejects a
 * turn_seq that is not the current one, which makes a double-submit or a
 * submission racing the timeout detectable rather than silently applied.
 *
 * @generated from message noitu.v1.SubmitWord
 */
export declare type SubmitWord = Message<"noitu.v1.SubmitWord"> & {
  /**
   * @generated from field: string word = 1;
   */
  word: string;

  /**
   * @generated from field: uint32 turn_seq = 2;
   */
  turnSeq: number;
};

/**
 * Describes the message noitu.v1.SubmitWord.
 * Use `create(SubmitWordSchema)` to create a new message.
 */
export declare const SubmitWordSchema: GenMessage<SubmitWord>;

/**
 * @generated from message noitu.v1.Resign
 */
export declare type Resign = Message<"noitu.v1.Resign"> & {
};

/**
 * Describes the message noitu.v1.Resign.
 * Use `create(ResignSchema)` to create a new message.
 */
export declare const ResignSchema: GenMessage<Resign>;

/**
 * SetReady is a guest declaring themselves ready, or taking it back.
 *
 * Only guests have a readiness to set. The owner's is implied by StartGame:
 * asking for the game to begin is the same statement, and a second flag they
 * would always have to set first buys nothing.
 *
 * @generated from message noitu.v1.SetReady
 */
export declare type SetReady = Message<"noitu.v1.SetReady"> & {
  /**
   * @generated from field: bool ready = 1;
   */
  ready: boolean;
};

/**
 * Describes the message noitu.v1.SetReady.
 * Use `create(SetReadySchema)` to create a new message.
 */
export declare const SetReadySchema: GenMessage<SetReady>;

/**
 * StartGame is the owner beginning the game the lobby has agreed on. It is
 * refused unless at least one guest is seated and every seated guest is
 * connected and ready.
 *
 * @generated from message noitu.v1.StartGame
 */
export declare type StartGame = Message<"noitu.v1.StartGame"> & {
};

/**
 * Describes the message noitu.v1.StartGame.
 * Use `create(StartGameSchema)` to create a new message.
 */
export declare const StartGameSchema: GenMessage<StartGame>;

/**
 * KickPlayer is the owner freeing one seat. Refused while that player is
 * ready: readiness is a commitment, and a player who has made it is not
 * something the owner gets to overrule.
 *
 * @generated from message noitu.v1.KickPlayer
 */
export declare type KickPlayer = Message<"noitu.v1.KickPlayer"> & {
  /**
   * Which seat, from RoomState.players. A room holds up to four people, so
   * "the other one" stopped being an answer.
   *
   * @generated from field: string player_id = 1;
   */
  playerId: string;
};

/**
 * Describes the message noitu.v1.KickPlayer.
 * Use `create(KickPlayerSchema)` to create a new message.
 */
export declare const KickPlayerSchema: GenMessage<KickPlayer>;

/**
 * LeaveRoom gives up a seat without dropping the connection, which is what
 * makes a room outlive one game rather than one visit. Refused while the
 * sender is ready — unreadying first is the deliberate friction.
 *
 * @generated from message noitu.v1.LeaveRoom
 */
export declare type LeaveRoom = Message<"noitu.v1.LeaveRoom"> & {
};

/**
 * Describes the message noitu.v1.LeaveRoom.
 * Use `create(LeaveRoomSchema)` to create a new message.
 */
export declare const LeaveRoomSchema: GenMessage<LeaveRoom>;

/**
 * SendChat is one line of text from a seated player to the other.
 *
 * @generated from message noitu.v1.SendChat
 */
export declare type SendChat = Message<"noitu.v1.SendChat"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message noitu.v1.SendChat.
 * Use `create(SendChatSchema)` to create a new message.
 */
export declare const SendChatSchema: GenMessage<SendChat>;

/**
 * Ping echoes the client clock so Pong can expose the offset between the two.
 *
 * @generated from message noitu.v1.Ping
 */
export declare type Ping = Message<"noitu.v1.Ping"> & {
  /**
   * @generated from field: int64 client_time_ms = 1;
   */
  clientTimeMs: bigint;
};

/**
 * Describes the message noitu.v1.Ping.
 * Use `create(PingSchema)` to create a new message.
 */
export declare const PingSchema: GenMessage<Ping>;

/**
 * @generated from message noitu.v1.ClientMessage
 */
export declare type ClientMessage = Message<"noitu.v1.ClientMessage"> & {
  /**
   * @generated from oneof noitu.v1.ClientMessage.payload
   */
  payload: {
    /**
     * @generated from field: noitu.v1.Hello hello = 1;
     */
    value: Hello;
    case: "hello";
  } | {
    /**
     * @generated from field: noitu.v1.StartBotGame start_bot_game = 2;
     */
    value: StartBotGame;
    case: "startBotGame";
  } | {
    /**
     * @generated from field: noitu.v1.CreateRoom create_room = 3;
     */
    value: CreateRoom;
    case: "createRoom";
  } | {
    /**
     * @generated from field: noitu.v1.JoinRoom join_room = 4;
     */
    value: JoinRoom;
    case: "joinRoom";
  } | {
    /**
     * @generated from field: noitu.v1.SubmitWord submit_word = 5;
     */
    value: SubmitWord;
    case: "submitWord";
  } | {
    /**
     * @generated from field: noitu.v1.Resign resign = 6;
     */
    value: Resign;
    case: "resign";
  } | {
    /**
     * @generated from field: noitu.v1.Ping ping = 7;
     */
    value: Ping;
    case: "ping";
  } | {
    /**
     * @generated from field: noitu.v1.SetReady set_ready = 9;
     */
    value: SetReady;
    case: "setReady";
  } | {
    /**
     * @generated from field: noitu.v1.StartGame start_game = 10;
     */
    value: StartGame;
    case: "startGame";
  } | {
    /**
     * @generated from field: noitu.v1.KickPlayer kick_player = 11;
     */
    value: KickPlayer;
    case: "kickPlayer";
  } | {
    /**
     * @generated from field: noitu.v1.LeaveRoom leave_room = 12;
     */
    value: LeaveRoom;
    case: "leaveRoom";
  } | {
    /**
     * @generated from field: noitu.v1.SendChat send_chat = 13;
     */
    value: SendChat;
    case: "sendChat";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message noitu.v1.ClientMessage.
 * Use `create(ClientMessageSchema)` to create a new message.
 */
export declare const ClientMessageSchema: GenMessage<ClientMessage>;

/**
 * @generated from message noitu.v1.Welcome
 */
export declare type Welcome = Message<"noitu.v1.Welcome"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string resume_token = 2;
   */
  resumeToken: string;

  /**
   * @generated from field: uint32 protocol_version = 3;
   */
  protocolVersion: number;

  /**
   * What the server stored after sanitizing Hello.nickname. The client must
   * display this, not the string it sent.
   *
   * @generated from field: string accepted_nickname = 4;
   */
  acceptedNickname: string;
};

/**
 * Describes the message noitu.v1.Welcome.
 * Use `create(WelcomeSchema)` to create a new message.
 */
export declare const WelcomeSchema: GenMessage<Welcome>;

/**
 * PlayedWord is one accepted move. word is the canonical spelling, which can
 * differ from what the player typed; typed preserves the raw input so the UI
 * can show that a correction happened instead of silently rewriting the text.
 *
 * @generated from message noitu.v1.PlayedWord
 */
export declare type PlayedWord = Message<"noitu.v1.PlayedWord"> & {
  /**
   * @generated from field: string word = 1;
   */
  word: string;

  /**
   * @generated from field: bool by_me = 2;
   */
  byMe: boolean;

  /**
   * @generated from field: uint32 points = 3;
   */
  points: number;

  /**
   * @generated from field: uint32 syllables = 4;
   */
  syllables: number;

  /**
   * @generated from field: string typed = 5;
   */
  typed: string;

  /**
   * Which seat played it. by_me answers "was this mine"; with four people at
   * the table the chain also has to say whose the other words were, and a seat
   * id says that without the client matching display names.
   *
   * @generated from field: string player_id = 6;
   */
  playerId: string;

  /**
   * What the word means, at most five senses. Empty when the dictionary has
   * no definition for the word; the client then says so rather than hiding
   * the row's panel, so every word in the chain behaves the same.
   *
   * @generated from field: repeated noitu.v1.Sense meanings = 7;
   */
  meanings: Sense[];
};

/**
 * Describes the message noitu.v1.PlayedWord.
 * Use `create(PlayedWordSchema)` to create a new message.
 */
export declare const PlayedWordSchema: GenMessage<PlayedWord>;

/**
 * Sense is one definition of a word as Wiktionary gives it: the part of
 * speech it sits under, in Vietnamese ("danh từ"), empty when the heading was
 * not one the builder knows, and the definition stripped of markup at at most
 * 200 characters. Plain text both: the client renders them as text, never as
 * markup.
 *
 * @generated from message noitu.v1.Sense
 */
export declare type Sense = Message<"noitu.v1.Sense"> & {
  /**
   * @generated from field: string pos = 1;
   */
  pos: string;

  /**
   * @generated from field: string gloss = 2;
   */
  gloss: string;
};

/**
 * Describes the message noitu.v1.Sense.
 * Use `create(SenseSchema)` to create a new message.
 */
export declare const SenseSchema: GenMessage<Sense>;

/**
 * PlayerSlot is one seat in the room, rendered for one recipient.
 *
 * The recipient's own row is in the list like everybody else's, marked by
 * is_me. That is deliberately the only way to find yourself: a separate
 * i_am_owner alongside an is_owner in the list would be two encodings of one
 * fact, and two ways for a client to disagree with the server.
 *
 * @generated from message noitu.v1.PlayerSlot
 */
export declare type PlayerSlot = Message<"noitu.v1.PlayerSlot"> & {
  /**
   * Stable for as long as this player holds the seat. Not stable across a
   * seat being vacated and refilled, which is exactly when a name stops
   * meaning the same person too.
   *
   * @generated from field: string player_id = 1;
   */
  playerId: string;

  /**
   * Always server-sanitized, as everywhere else another player's name appears.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: bool is_me = 3;
   */
  isMe: boolean;

  /**
   * @generated from field: bool is_owner = 4;
   */
  isOwner: boolean;

  /**
   * Always false for the owner, whose readiness is StartGame itself.
   *
   * @generated from field: bool ready = 5;
   */
  ready: boolean;

  /**
   * False while this player is inside their reconnect window.
   *
   * @generated from field: bool connected = 6;
   */
  connected: boolean;

  /**
   * How many games this seat has won since the room opened. A room outlives
   * its games, so the tally belongs to the seat rather than to any one of
   * them; it starts again when the seat is vacated, because by then the name
   * on it no longer means the same person.
   *
   * @generated from field: uint32 wins = 7;
   */
  wins: number;
};

/**
 * Describes the message noitu.v1.PlayerSlot.
 * Use `create(PlayerSlotSchema)` to create a new message.
 */
export declare const PlayerSlotSchema: GenMessage<PlayerSlot>;

/**
 * PlayerScore is one player in a running or finished game.
 *
 * Separate from PlayerSlot because they answer different questions: a slot is
 * about the room, a score is about the game being played in it. A player who
 * has been eliminated still has both — being out of the game is not being out
 * of the room.
 *
 * @generated from message noitu.v1.PlayerScore
 */
export declare type PlayerScore = Message<"noitu.v1.PlayerScore"> & {
  /**
   * @generated from field: string player_id = 1;
   */
  playerId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: bool is_me = 3;
   */
  isMe: boolean;

  /**
   * @generated from field: uint32 score = 4;
   */
  score: number;

  /**
   * True once this player has been knocked out. They keep their seat, their
   * score and their words; they simply no longer get a turn.
   *
   * @generated from field: bool eliminated = 5;
   */
  eliminated: boolean;

  /**
   * @generated from field: bool connected = 6;
   */
  connected: boolean;

  /**
   * Final placing, 1 for the winner. Zero while the game is still running,
   * which is what tells the two apart without a second field.
   *
   * @generated from field: uint32 rank = 7;
   */
  rank: number;
};

/**
 * Describes the message noitu.v1.PlayerScore.
 * Use `create(PlayerScoreSchema)` to create a new message.
 */
export declare const PlayerScoreSchema: GenMessage<PlayerScore>;

/**
 * GameStarted is rendered per recipient: my_turn is true for exactly one
 * player.
 *
 * @generated from message noitu.v1.GameStarted
 */
export declare type GameStarted = Message<"noitu.v1.GameStarted"> & {
  /**
   * @generated from field: string opening_word = 1;
   */
  openingWord: string;

  /**
   * @generated from field: string current_syllable = 2;
   */
  currentSyllable: string;

  /**
   * @generated from field: bool my_turn = 3;
   */
  myTurn: boolean;

  /**
   * Absolute server timestamp. The client counts down to it and never trusts
   * its own clock for authority.
   *
   * @generated from field: int64 deadline_unix_ms = 4;
   */
  deadlineUnixMs: bigint;

  /**
   * @generated from field: uint32 turn_seq = 5;
   */
  turnSeq: number;

  /**
   * @generated from field: uint32 turn_limit_ms = 6;
   */
  turnLimitMs: number;

  /**
   * Everyone playing, in turn order.
   *
   * @generated from field: repeated noitu.v1.PlayerScore players = 7;
   */
  players: PlayerScore[];

  /**
   * Whose turn it is. my_turn above says whether it is yours; this says whose
   * it is when it is not, which a two-player game never had to.
   *
   * @generated from field: string turn_player_id = 8;
   */
  turnPlayerId: string;

  /**
   * The opening word's senses, as PlayedWord.meanings for a played word.
   *
   * @generated from field: repeated noitu.v1.Sense opening_meanings = 9;
   */
  openingMeanings: Sense[];
};

/**
 * Describes the message noitu.v1.GameStarted.
 * Use `create(GameStartedSchema)` to create a new message.
 */
export declare const GameStartedSchema: GenMessage<GameStarted>;

/**
 * TurnUpdate follows every turn change and goes to every player, serialized
 * once per recipient so by_me and my_turn are correct for each.
 *
 * played is absent when the turn moved without a word being played, which is
 * what an elimination does: the syllable and the used set survive the player
 * who could not answer them. It is also absent when the turn did not move at
 * all — a player behind the one to act forfeiting, by leaving the room or by
 * never coming back to it — and then turn_seq is unchanged too, because the
 * word the player to act is already sending still answers this position.
 *
 * @generated from message noitu.v1.TurnUpdate
 */
export declare type TurnUpdate = Message<"noitu.v1.TurnUpdate"> & {
  /**
   * @generated from field: noitu.v1.PlayedWord played = 1;
   */
  played?: PlayedWord | undefined;

  /**
   * @generated from field: string current_syllable = 2;
   */
  currentSyllable: string;

  /**
   * @generated from field: bool my_turn = 3;
   */
  myTurn: boolean;

  /**
   * @generated from field: int64 deadline_unix_ms = 4;
   */
  deadlineUnixMs: bigint;

  /**
   * @generated from field: uint32 turn_seq = 5;
   */
  turnSeq: number;

  /**
   * @generated from field: uint32 chain_length = 8;
   */
  chainLength: number;

  /**
   * Everyone playing, in turn order, with scores as they stand.
   *
   * @generated from field: repeated noitu.v1.PlayerScore players = 9;
   */
  players: PlayerScore[];

  /**
   * @generated from field: string turn_player_id = 10;
   */
  turnPlayerId: string;
};

/**
 * Describes the message noitu.v1.TurnUpdate.
 * Use `create(TurnUpdateSchema)` to create a new message.
 */
export declare const TurnUpdateSchema: GenMessage<TurnUpdate>;

/**
 * @generated from message noitu.v1.MoveRejected
 */
export declare type MoveRejected = Message<"noitu.v1.MoveRejected"> & {
  /**
   * @generated from field: noitu.v1.RejectReason reason = 1;
   */
  reason: RejectReason;

  /**
   * @generated from field: string word = 2;
   */
  word: string;

  /**
   * @generated from field: uint32 turn_seq = 3;
   */
  turnSeq: number;
};

/**
 * Describes the message noitu.v1.MoveRejected.
 * Use `create(MoveRejectedSchema)` to create a new message.
 */
export declare const MoveRejectedSchema: GenMessage<MoveRejected>;

/**
 * GameOver is rendered per recipient: i_won is true for exactly one player,
 * the one still standing when everybody else had been eliminated.
 *
 * @generated from message noitu.v1.GameOver
 */
export declare type GameOver = Message<"noitu.v1.GameOver"> & {
  /**
   * @generated from field: bool i_won = 1;
   */
  iWon: boolean;

  /**
   * @generated from field: noitu.v1.GameEndReason reason = 2;
   */
  reason: GameEndReason;

  /**
   * @generated from field: uint32 chain_length = 4;
   */
  chainLength: number;

  /**
   * The final table, best first: the player left standing, then the others in
   * reverse order of elimination. Outlasting somebody is what beats them, so
   * the ranking is finishing order and each score is reported beside it rather
   * than deciding it.
   *
   * @generated from field: repeated noitu.v1.PlayerScore standings = 6;
   */
  standings: PlayerScore[];
};

/**
 * Describes the message noitu.v1.GameOver.
 * Use `create(GameOverSchema)` to create a new message.
 */
export declare const GameOverSchema: GenMessage<GameOver>;

/**
 * PlayerEliminated is one player knocked out of a game that is still running.
 *
 * Rendered per recipient like everything else in a room, and the only message
 * whose contents differ by more than a flag: suggestions are filled in solely
 * for the player who went out, because they are the one who was stuck.
 *
 * @generated from message noitu.v1.PlayerEliminated
 */
export declare type PlayerEliminated = Message<"noitu.v1.PlayerEliminated"> & {
  /**
   * @generated from field: string player_id = 1;
   */
  playerId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: bool is_me = 3;
   */
  isMe: boolean;

  /**
   * @generated from field: noitu.v1.GameEndReason reason = 4;
   */
  reason: GameEndReason;

  /**
   * A few words the position still had, for the player who just lost it. An
   * empty list is itself the answer: nobody could have answered that syllable.
   *
   * @generated from field: repeated string suggestions = 5;
   */
  suggestions: string[];
};

/**
 * Describes the message noitu.v1.PlayerEliminated.
 * Use `create(PlayerEliminatedSchema)` to create a new message.
 */
export declare const PlayerEliminatedSchema: GenMessage<PlayerEliminated>;

/**
 * ServerError.message is a UI key such as "room_not_found", never prose: all
 * Vietnamese copy lives in the frontend so it stays in one place.
 *
 * @generated from message noitu.v1.ServerError
 */
export declare type ServerError = Message<"noitu.v1.ServerError"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message noitu.v1.ServerError.
 * Use `create(ServerErrorSchema)` to create a new message.
 */
export declare const ServerErrorSchema: GenMessage<ServerError>;

/**
 * @generated from message noitu.v1.Pong
 */
export declare type Pong = Message<"noitu.v1.Pong"> & {
  /**
   * @generated from field: int64 client_time_ms = 1;
   */
  clientTimeMs: bigint;

  /**
   * @generated from field: int64 server_time_ms = 2;
   */
  serverTimeMs: bigint;
};

/**
 * Describes the message noitu.v1.Pong.
 * Use `create(PongSchema)` to create a new message.
 */
export declare const PongSchema: GenMessage<Pong>;

/**
 * RoomState is the whole room, rendered for one recipient, and it is the only
 * thing the lobby screen is built from. Sent on every change a player could
 * see — a seat filled or freed, a readiness set, an owner promoted, somebody
 * dropping or coming back — and again on resume, so a client that missed a
 * frame recovers by being told the state rather than by replaying the events
 * that led to it.
 *
 * It describes the room, not the game, so it is meaningful during one too:
 * while a game runs this is what carries presence, which is why there is no
 * separate message for a player disconnecting.
 *
 * @generated from message noitu.v1.RoomState
 */
export declare type RoomState = Message<"noitu.v1.RoomState"> & {
  /**
   * @generated from field: string room_code = 1;
   */
  roomCode: string;

  /**
   * Whether StartGame would be accepted right now. The server decides this
   * because it owns every condition that feeds it.
   *
   * @generated from field: bool can_start = 3;
   */
  canStart: boolean;

  /**
   * Everyone seated, in seat order, which is also the turn order a game will
   * use. Always includes the recipient, marked is_me.
   *
   * @generated from field: repeated noitu.v1.PlayerSlot players = 9;
   */
  players: PlayerSlot[];

  /**
   * How many seats the room has and how many players a game needs. Sent
   * rather than compiled in, so the lobby draws whatever the server allows and
   * raising the limit does not need a client deploy.
   *
   * @generated from field: uint32 max_players = 10;
   */
  maxPlayers: number;

  /**
   * @generated from field: uint32 min_players = 11;
   */
  minPlayers: number;

  /**
   * How long a seat is held for a player who has dropped. The client counts
   * down against it for anybody whose connected is false; the server still
   * decides when the seat is actually forfeit.
   *
   * @generated from field: uint32 grace_ms = 12;
   */
  graceMs: number;
};

/**
 * Describes the message noitu.v1.RoomState.
 * Use `create(RoomStateSchema)` to create a new message.
 */
export declare const RoomStateSchema: GenMessage<RoomState>;

/**
 * ChatMessage is one line as one recipient sees it. Rendered per recipient
 * like every other room message: from_me is the only field that differs, and
 * it is what lets the client style its own words without matching names.
 *
 * @generated from message noitu.v1.ChatMessage
 */
export declare type ChatMessage = Message<"noitu.v1.ChatMessage"> & {
  /**
   * @generated from field: bool from_me = 1;
   */
  fromMe: boolean;

  /**
   * Server-sanitized, as everywhere a name is shown. Empty when the author has
   * left the room: the seat they spoke from may be somebody else's now, and a
   * name outlives neither. The client labels an empty author itself.
   *
   * @generated from field: string author = 2;
   */
  author: string;

  /**
   * @generated from field: string text = 3;
   */
  text: string;

  /**
   * Server clock. The client renders it; it never orders by its own clock.
   *
   * @generated from field: int64 sent_unix_ms = 4;
   */
  sentUnixMs: bigint;

  /**
   * Which seat spoke, so the client can colour a line by its author instead
   * of by matching display names. Cleared with the author for a line whose
   * seat has been vacated.
   *
   * @generated from field: string player_id = 5;
   */
  playerId: string;
};

/**
 * Describes the message noitu.v1.ChatMessage.
 * Use `create(ChatMessageSchema)` to create a new message.
 */
export declare const ChatMessageSchema: GenMessage<ChatMessage>;

/**
 * ChatHistory is the whole panel, oldest first, sent when a player is seated in
 * a room or resumes into one. A snapshot rather than a replayed stream, for the
 * same reason RoomState is one: a client that missed frames is correct again
 * from the next one instead of having to catch up on events.
 *
 * Scoped to the recipient: it carries only what was said while they held their
 * seat, which is why it is built per seat rather than broadcast.
 *
 * @generated from message noitu.v1.ChatHistory
 */
export declare type ChatHistory = Message<"noitu.v1.ChatHistory"> & {
  /**
   * @generated from field: repeated noitu.v1.ChatMessage messages = 1;
   */
  messages: ChatMessage[];
};

/**
 * Describes the message noitu.v1.ChatHistory.
 * Use `create(ChatHistorySchema)` to create a new message.
 */
export declare const ChatHistorySchema: GenMessage<ChatHistory>;

/**
 * @generated from message noitu.v1.ServerMessage
 */
export declare type ServerMessage = Message<"noitu.v1.ServerMessage"> & {
  /**
   * @generated from oneof noitu.v1.ServerMessage.payload
   */
  payload: {
    /**
     * @generated from field: noitu.v1.Welcome welcome = 1;
     */
    value: Welcome;
    case: "welcome";
  } | {
    /**
     * @generated from field: noitu.v1.GameStarted game_started = 4;
     */
    value: GameStarted;
    case: "gameStarted";
  } | {
    /**
     * @generated from field: noitu.v1.TurnUpdate turn_update = 5;
     */
    value: TurnUpdate;
    case: "turnUpdate";
  } | {
    /**
     * @generated from field: noitu.v1.MoveRejected move_rejected = 6;
     */
    value: MoveRejected;
    case: "moveRejected";
  } | {
    /**
     * @generated from field: noitu.v1.GameOver game_over = 7;
     */
    value: GameOver;
    case: "gameOver";
  } | {
    /**
     * @generated from field: noitu.v1.ServerError error = 9;
     */
    value: ServerError;
    case: "error";
  } | {
    /**
     * @generated from field: noitu.v1.Pong pong = 10;
     */
    value: Pong;
    case: "pong";
  } | {
    /**
     * @generated from field: noitu.v1.RoomState room_state = 12;
     */
    value: RoomState;
    case: "roomState";
  } | {
    /**
     * @generated from field: noitu.v1.ChatMessage chat_message = 13;
     */
    value: ChatMessage;
    case: "chatMessage";
  } | {
    /**
     * @generated from field: noitu.v1.ChatHistory chat_history = 14;
     */
    value: ChatHistory;
    case: "chatHistory";
  } | {
    /**
     * @generated from field: noitu.v1.PlayerEliminated player_eliminated = 15;
     */
    value: PlayerEliminated;
    case: "playerEliminated";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message noitu.v1.ServerMessage.
 * Use `create(ServerMessageSchema)` to create a new message.
 */
export declare const ServerMessageSchema: GenMessage<ServerMessage>;

/**
 * Difficulty selects the bot's strategy in a vs-bot game.
 *
 * @generated from enum noitu.v1.Difficulty
 */
export enum Difficulty {
  /**
   * @generated from enum value: DIFFICULTY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DIFFICULTY_EASY = 1;
   */
  EASY = 1,

  /**
   * @generated from enum value: DIFFICULTY_MEDIUM = 2;
   */
  MEDIUM = 2,

  /**
   * @generated from enum value: DIFFICULTY_HARD = 3;
   */
  HARD = 3,
}

/**
 * Describes the enum noitu.v1.Difficulty.
 */
export declare const DifficultySchema: GenEnum<Difficulty>;

/**
 * RejectReason says why a submitted word was not accepted. It is deliberately
 * a separate type from the engine's internal game.RejectReason: the wire
 * contract must not change every time the engine is refactored. The mapping
 * lives in server/internal/wsapi/convert.go.
 *
 * @generated from enum noitu.v1.RejectReason
 */
export enum RejectReason {
  /**
   * @generated from enum value: REJECT_REASON_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Fewer than two syllables.
   *
   * @generated from enum value: REJECT_REASON_TOO_FEW_SYLLABLES = 1;
   */
  TOO_FEW_SYLLABLES = 1,

  /**
   * First syllable does not match the required syllable.
   *
   * @generated from enum value: REJECT_REASON_WRONG_LINK = 2;
   */
  WRONG_LINK = 2,

  /**
   * @generated from enum value: REJECT_REASON_NOT_IN_DICTIONARY = 3;
   */
  NOT_IN_DICTIONARY = 3,

  /**
   * @generated from enum value: REJECT_REASON_ALREADY_USED = 4;
   */
  ALREADY_USED = 4,

  /**
   * @generated from enum value: REJECT_REASON_NOT_YOUR_TURN = 5;
   */
  NOT_YOUR_TURN = 5,

  /**
   * The turn deadline passed before the word arrived.
   *
   * @generated from enum value: REJECT_REASON_TIMEOUT = 6;
   */
  TIMEOUT = 6,

  /**
   * The game had already finished.
   *
   * @generated from enum value: REJECT_REASON_GAME_OVER = 7;
   */
  GAME_OVER = 7,
}

/**
 * Describes the enum noitu.v1.RejectReason.
 */
export declare const RejectReasonSchema: GenEnum<RejectReason>;

/**
 * GameEndReason says how a finished game ended.
 *
 * @generated from enum noitu.v1.GameEndReason
 */
export enum GameEndReason {
  /**
   * @generated from enum value: GAME_END_REASON_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GAME_END_REASON_TIMEOUT = 1;
   */
  TIMEOUT = 1,

  /**
   * @generated from enum value: GAME_END_REASON_NO_LEGAL_MOVE = 2;
   */
  NO_LEGAL_MOVE = 2,

  /**
   * @generated from enum value: GAME_END_REASON_OPPONENT_LEFT = 3;
   */
  OPPONENT_LEFT = 3,

  /**
   * @generated from enum value: GAME_END_REASON_RESIGNED = 4;
   */
  RESIGNED = 4,
}

/**
 * Describes the enum noitu.v1.GameEndReason.
 */
export declare const GameEndReasonSchema: GenEnum<GameEndReason>;

