// The nối từ wire contract.
//
// This file is the single source of truth for everything crossing the
// WebSocket. Both the Go server and the JavaScript client are generated from
// it; neither side hand-writes a message type. Every frame is a binary
// protobuf message — there is no JSON fallback and no text frame.
//
// Compatibility rules, because a deployed client outlives a deploy:
//   - changes are additive only;
//   - a removed field's tag goes to `reserved`, never to another field;
//   - Hello.protocol_version lets the server refuse an incompatible client
//     with a readable error instead of failing to decode.

// @generated by protoc-gen-es v2.14.1 with parameter "target=js+dts,import_extension=.js"
// @generated from file noitu/v1/game.proto (package noitu.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file noitu/v1/game.proto.
 */
export declare const file_noitu_v1_game: GenFile;

/**
 * Hello opens a session. nickname is a *request*: the server sanitizes it and
 * reports what it actually stored in Welcome.accepted_nickname.
 *
 * @generated from message noitu.v1.Hello
 */
export declare type Hello = Message<"noitu.v1.Hello"> & {
  /**
   * @generated from field: uint32 protocol_version = 1;
   */
  protocolVersion: number;

  /**
   * Empty on a fresh session; a token from a previous Welcome to resume one.
   *
   * @generated from field: string resume_token = 2;
   */
  resumeToken: string;

  /**
   * @generated from field: string nickname = 3;
   */
  nickname: string;
};

/**
 * Describes the message noitu.v1.Hello.
 * Use `create(HelloSchema)` to create a new message.
 */
export declare const HelloSchema: GenMessage<Hello>;

/**
 * @generated from message noitu.v1.StartBotGame
 */
export declare type StartBotGame = Message<"noitu.v1.StartBotGame"> & {
  /**
   * @generated from field: noitu.v1.Difficulty difficulty = 1;
   */
  difficulty: Difficulty;
};

/**
 * Describes the message noitu.v1.StartBotGame.
 * Use `create(StartBotGameSchema)` to create a new message.
 */
export declare const StartBotGameSchema: GenMessage<StartBotGame>;

/**
 * @generated from message noitu.v1.CreateRoom
 */
export declare type CreateRoom = Message<"noitu.v1.CreateRoom"> & {
};

/**
 * Describes the message noitu.v1.CreateRoom.
 * Use `create(CreateRoomSchema)` to create a new message.
 */
export declare const CreateRoomSchema: GenMessage<CreateRoom>;

/**
 * @generated from message noitu.v1.JoinRoom
 */
export declare type JoinRoom = Message<"noitu.v1.JoinRoom"> & {
  /**
   * @generated from field: string room_code = 1;
   */
  roomCode: string;
};

/**
 * Describes the message noitu.v1.JoinRoom.
 * Use `create(JoinRoomSchema)` to create a new message.
 */
export declare const JoinRoomSchema: GenMessage<JoinRoom>;

/**
 * SubmitWord carries the turn it was typed for. The server rejects a
 * turn_seq that is not the current one, which makes a double-submit or a
 * submission racing the timeout detectable rather than silently applied.
 *
 * @generated from message noitu.v1.SubmitWord
 */
export declare type SubmitWord = Message<"noitu.v1.SubmitWord"> & {
  /**
   * @generated from field: string word = 1;
   */
  word: string;

  /**
   * @generated from field: uint32 turn_seq = 2;
   */
  turnSeq: number;
};

/**
 * Describes the message noitu.v1.SubmitWord.
 * Use `create(SubmitWordSchema)` to create a new message.
 */
export declare const SubmitWordSchema: GenMessage<SubmitWord>;

/**
 * @generated from message noitu.v1.Resign
 */
export declare type Resign = Message<"noitu.v1.Resign"> & {
};

/**
 * Describes the message noitu.v1.Resign.
 * Use `create(ResignSchema)` to create a new message.
 */
export declare const ResignSchema: GenMessage<Resign>;

/**
 * Ping echoes the client clock so Pong can expose the offset between the two.
 *
 * @generated from message noitu.v1.Ping
 */
export declare type Ping = Message<"noitu.v1.Ping"> & {
  /**
   * @generated from field: int64 client_time_ms = 1;
   */
  clientTimeMs: bigint;
};

/**
 * Describes the message noitu.v1.Ping.
 * Use `create(PingSchema)` to create a new message.
 */
export declare const PingSchema: GenMessage<Ping>;

/**
 * @generated from message noitu.v1.ClientMessage
 */
export declare type ClientMessage = Message<"noitu.v1.ClientMessage"> & {
  /**
   * @generated from oneof noitu.v1.ClientMessage.payload
   */
  payload: {
    /**
     * @generated from field: noitu.v1.Hello hello = 1;
     */
    value: Hello;
    case: "hello";
  } | {
    /**
     * @generated from field: noitu.v1.StartBotGame start_bot_game = 2;
     */
    value: StartBotGame;
    case: "startBotGame";
  } | {
    /**
     * @generated from field: noitu.v1.CreateRoom create_room = 3;
     */
    value: CreateRoom;
    case: "createRoom";
  } | {
    /**
     * @generated from field: noitu.v1.JoinRoom join_room = 4;
     */
    value: JoinRoom;
    case: "joinRoom";
  } | {
    /**
     * @generated from field: noitu.v1.SubmitWord submit_word = 5;
     */
    value: SubmitWord;
    case: "submitWord";
  } | {
    /**
     * @generated from field: noitu.v1.Resign resign = 6;
     */
    value: Resign;
    case: "resign";
  } | {
    /**
     * @generated from field: noitu.v1.Ping ping = 7;
     */
    value: Ping;
    case: "ping";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message noitu.v1.ClientMessage.
 * Use `create(ClientMessageSchema)` to create a new message.
 */
export declare const ClientMessageSchema: GenMessage<ClientMessage>;

/**
 * @generated from message noitu.v1.Welcome
 */
export declare type Welcome = Message<"noitu.v1.Welcome"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string resume_token = 2;
   */
  resumeToken: string;

  /**
   * @generated from field: uint32 protocol_version = 3;
   */
  protocolVersion: number;

  /**
   * What the server stored after sanitizing Hello.nickname. The client must
   * display this, not the string it sent.
   *
   * @generated from field: string accepted_nickname = 4;
   */
  acceptedNickname: string;
};

/**
 * Describes the message noitu.v1.Welcome.
 * Use `create(WelcomeSchema)` to create a new message.
 */
export declare const WelcomeSchema: GenMessage<Welcome>;

/**
 * @generated from message noitu.v1.RoomCreated
 */
export declare type RoomCreated = Message<"noitu.v1.RoomCreated"> & {
  /**
   * @generated from field: string room_code = 1;
   */
  roomCode: string;
};

/**
 * Describes the message noitu.v1.RoomCreated.
 * Use `create(RoomCreatedSchema)` to create a new message.
 */
export declare const RoomCreatedSchema: GenMessage<RoomCreated>;

/**
 * @generated from message noitu.v1.RoomJoined
 */
export declare type RoomJoined = Message<"noitu.v1.RoomJoined"> & {
  /**
   * @generated from field: string room_code = 1;
   */
  roomCode: string;

  /**
   * Always server-sanitized. A client must never render another player's raw
   * input.
   *
   * @generated from field: string opponent_name = 2;
   */
  opponentName: string;
};

/**
 * Describes the message noitu.v1.RoomJoined.
 * Use `create(RoomJoinedSchema)` to create a new message.
 */
export declare const RoomJoinedSchema: GenMessage<RoomJoined>;

/**
 * PlayedWord is one accepted move. word is the canonical spelling, which can
 * differ from what the player typed; typed preserves the raw input so the UI
 * can show that a correction happened instead of silently rewriting the text.
 *
 * @generated from message noitu.v1.PlayedWord
 */
export declare type PlayedWord = Message<"noitu.v1.PlayedWord"> & {
  /**
   * @generated from field: string word = 1;
   */
  word: string;

  /**
   * @generated from field: bool by_me = 2;
   */
  byMe: boolean;

  /**
   * @generated from field: uint32 points = 3;
   */
  points: number;

  /**
   * @generated from field: uint32 syllables = 4;
   */
  syllables: number;

  /**
   * @generated from field: string typed = 5;
   */
  typed: string;
};

/**
 * Describes the message noitu.v1.PlayedWord.
 * Use `create(PlayedWordSchema)` to create a new message.
 */
export declare const PlayedWordSchema: GenMessage<PlayedWord>;

/**
 * GameStarted is rendered per recipient: my_turn is true for exactly one of
 * the two players.
 *
 * @generated from message noitu.v1.GameStarted
 */
export declare type GameStarted = Message<"noitu.v1.GameStarted"> & {
  /**
   * @generated from field: string opening_word = 1;
   */
  openingWord: string;

  /**
   * @generated from field: string current_syllable = 2;
   */
  currentSyllable: string;

  /**
   * @generated from field: bool my_turn = 3;
   */
  myTurn: boolean;

  /**
   * Absolute server timestamp. The client counts down to it and never trusts
   * its own clock for authority.
   *
   * @generated from field: int64 deadline_unix_ms = 4;
   */
  deadlineUnixMs: bigint;

  /**
   * @generated from field: uint32 turn_seq = 5;
   */
  turnSeq: number;

  /**
   * @generated from field: uint32 turn_limit_ms = 6;
   */
  turnLimitMs: number;
};

/**
 * Describes the message noitu.v1.GameStarted.
 * Use `create(GameStartedSchema)` to create a new message.
 */
export declare const GameStartedSchema: GenMessage<GameStarted>;

/**
 * TurnUpdate follows every accepted move and goes to both players, serialized
 * once per recipient so by_me and my_turn are correct for each.
 *
 * @generated from message noitu.v1.TurnUpdate
 */
export declare type TurnUpdate = Message<"noitu.v1.TurnUpdate"> & {
  /**
   * @generated from field: noitu.v1.PlayedWord played = 1;
   */
  played?: PlayedWord | undefined;

  /**
   * @generated from field: string current_syllable = 2;
   */
  currentSyllable: string;

  /**
   * @generated from field: bool my_turn = 3;
   */
  myTurn: boolean;

  /**
   * @generated from field: int64 deadline_unix_ms = 4;
   */
  deadlineUnixMs: bigint;

  /**
   * @generated from field: uint32 turn_seq = 5;
   */
  turnSeq: number;

  /**
   * @generated from field: uint32 my_score = 6;
   */
  myScore: number;

  /**
   * @generated from field: uint32 opponent_score = 7;
   */
  opponentScore: number;

  /**
   * @generated from field: uint32 chain_length = 8;
   */
  chainLength: number;
};

/**
 * Describes the message noitu.v1.TurnUpdate.
 * Use `create(TurnUpdateSchema)` to create a new message.
 */
export declare const TurnUpdateSchema: GenMessage<TurnUpdate>;

/**
 * @generated from message noitu.v1.MoveRejected
 */
export declare type MoveRejected = Message<"noitu.v1.MoveRejected"> & {
  /**
   * @generated from field: noitu.v1.RejectReason reason = 1;
   */
  reason: RejectReason;

  /**
   * @generated from field: string word = 2;
   */
  word: string;

  /**
   * @generated from field: uint32 turn_seq = 3;
   */
  turnSeq: number;
};

/**
 * Describes the message noitu.v1.MoveRejected.
 * Use `create(MoveRejectedSchema)` to create a new message.
 */
export declare const MoveRejectedSchema: GenMessage<MoveRejected>;

/**
 * @generated from message noitu.v1.GameOver
 */
export declare type GameOver = Message<"noitu.v1.GameOver"> & {
  /**
   * @generated from field: bool i_won = 1;
   */
  iWon: boolean;

  /**
   * @generated from field: noitu.v1.GameEndReason reason = 2;
   */
  reason: GameEndReason;

  /**
   * @generated from field: uint32 my_score = 3;
   */
  myScore: number;

  /**
   * @generated from field: uint32 chain_length = 4;
   */
  chainLength: number;
};

/**
 * Describes the message noitu.v1.GameOver.
 * Use `create(GameOverSchema)` to create a new message.
 */
export declare const GameOverSchema: GenMessage<GameOver>;

/**
 * @generated from message noitu.v1.OpponentLeft
 */
export declare type OpponentLeft = Message<"noitu.v1.OpponentLeft"> & {
  /**
   * @generated from field: bool can_reconnect = 1;
   */
  canReconnect: boolean;

  /**
   * @generated from field: uint32 grace_ms = 2;
   */
  graceMs: number;
};

/**
 * Describes the message noitu.v1.OpponentLeft.
 * Use `create(OpponentLeftSchema)` to create a new message.
 */
export declare const OpponentLeftSchema: GenMessage<OpponentLeft>;

/**
 * ServerError.message is a UI key such as "room_not_found", never prose: all
 * Vietnamese copy lives in the frontend so it stays in one place.
 *
 * @generated from message noitu.v1.ServerError
 */
export declare type ServerError = Message<"noitu.v1.ServerError"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message noitu.v1.ServerError.
 * Use `create(ServerErrorSchema)` to create a new message.
 */
export declare const ServerErrorSchema: GenMessage<ServerError>;

/**
 * @generated from message noitu.v1.Pong
 */
export declare type Pong = Message<"noitu.v1.Pong"> & {
  /**
   * @generated from field: int64 client_time_ms = 1;
   */
  clientTimeMs: bigint;

  /**
   * @generated from field: int64 server_time_ms = 2;
   */
  serverTimeMs: bigint;
};

/**
 * Describes the message noitu.v1.Pong.
 * Use `create(PongSchema)` to create a new message.
 */
export declare const PongSchema: GenMessage<Pong>;

/**
 * @generated from message noitu.v1.ServerMessage
 */
export declare type ServerMessage = Message<"noitu.v1.ServerMessage"> & {
  /**
   * @generated from oneof noitu.v1.ServerMessage.payload
   */
  payload: {
    /**
     * @generated from field: noitu.v1.Welcome welcome = 1;
     */
    value: Welcome;
    case: "welcome";
  } | {
    /**
     * @generated from field: noitu.v1.RoomCreated room_created = 2;
     */
    value: RoomCreated;
    case: "roomCreated";
  } | {
    /**
     * @generated from field: noitu.v1.RoomJoined room_joined = 3;
     */
    value: RoomJoined;
    case: "roomJoined";
  } | {
    /**
     * @generated from field: noitu.v1.GameStarted game_started = 4;
     */
    value: GameStarted;
    case: "gameStarted";
  } | {
    /**
     * @generated from field: noitu.v1.TurnUpdate turn_update = 5;
     */
    value: TurnUpdate;
    case: "turnUpdate";
  } | {
    /**
     * @generated from field: noitu.v1.MoveRejected move_rejected = 6;
     */
    value: MoveRejected;
    case: "moveRejected";
  } | {
    /**
     * @generated from field: noitu.v1.GameOver game_over = 7;
     */
    value: GameOver;
    case: "gameOver";
  } | {
    /**
     * @generated from field: noitu.v1.OpponentLeft opponent_left = 8;
     */
    value: OpponentLeft;
    case: "opponentLeft";
  } | {
    /**
     * @generated from field: noitu.v1.ServerError error = 9;
     */
    value: ServerError;
    case: "error";
  } | {
    /**
     * @generated from field: noitu.v1.Pong pong = 10;
     */
    value: Pong;
    case: "pong";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message noitu.v1.ServerMessage.
 * Use `create(ServerMessageSchema)` to create a new message.
 */
export declare const ServerMessageSchema: GenMessage<ServerMessage>;

/**
 * Difficulty selects the bot's strategy in a vs-bot game.
 *
 * @generated from enum noitu.v1.Difficulty
 */
export enum Difficulty {
  /**
   * @generated from enum value: DIFFICULTY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: DIFFICULTY_EASY = 1;
   */
  EASY = 1,

  /**
   * @generated from enum value: DIFFICULTY_MEDIUM = 2;
   */
  MEDIUM = 2,

  /**
   * @generated from enum value: DIFFICULTY_HARD = 3;
   */
  HARD = 3,
}

/**
 * Describes the enum noitu.v1.Difficulty.
 */
export declare const DifficultySchema: GenEnum<Difficulty>;

/**
 * RejectReason says why a submitted word was not accepted. It is deliberately
 * a separate type from the engine's internal game.RejectReason: the wire
 * contract must not change every time the engine is refactored. The mapping
 * lives in server/internal/wsapi/convert.go.
 *
 * @generated from enum noitu.v1.RejectReason
 */
export enum RejectReason {
  /**
   * @generated from enum value: REJECT_REASON_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Fewer than two syllables.
   *
   * @generated from enum value: REJECT_REASON_TOO_FEW_SYLLABLES = 1;
   */
  TOO_FEW_SYLLABLES = 1,

  /**
   * First syllable does not match the required syllable.
   *
   * @generated from enum value: REJECT_REASON_WRONG_LINK = 2;
   */
  WRONG_LINK = 2,

  /**
   * @generated from enum value: REJECT_REASON_NOT_IN_DICTIONARY = 3;
   */
  NOT_IN_DICTIONARY = 3,

  /**
   * @generated from enum value: REJECT_REASON_ALREADY_USED = 4;
   */
  ALREADY_USED = 4,

  /**
   * @generated from enum value: REJECT_REASON_NOT_YOUR_TURN = 5;
   */
  NOT_YOUR_TURN = 5,

  /**
   * The turn deadline passed before the word arrived.
   *
   * @generated from enum value: REJECT_REASON_TIMEOUT = 6;
   */
  TIMEOUT = 6,

  /**
   * The game had already finished.
   *
   * @generated from enum value: REJECT_REASON_GAME_OVER = 7;
   */
  GAME_OVER = 7,
}

/**
 * Describes the enum noitu.v1.RejectReason.
 */
export declare const RejectReasonSchema: GenEnum<RejectReason>;

/**
 * GameEndReason says how a finished game ended.
 *
 * @generated from enum noitu.v1.GameEndReason
 */
export enum GameEndReason {
  /**
   * @generated from enum value: GAME_END_REASON_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GAME_END_REASON_TIMEOUT = 1;
   */
  TIMEOUT = 1,

  /**
   * @generated from enum value: GAME_END_REASON_NO_LEGAL_MOVE = 2;
   */
  NO_LEGAL_MOVE = 2,

  /**
   * @generated from enum value: GAME_END_REASON_OPPONENT_LEFT = 3;
   */
  OPPONENT_LEFT = 3,

  /**
   * @generated from enum value: GAME_END_REASON_RESIGNED = 4;
   */
  RESIGNED = 4,
}

/**
 * Describes the enum noitu.v1.GameEndReason.
 */
export declare const GameEndReasonSchema: GenEnum<GameEndReason>;

